deepin-community/linyaps

.github/workflows/call-auto-tag.yml, .github/workflows/call-build-deb.yml, .github/workflows/call-build-tag.yml, .github/workflows/call-chatOps.yml
github workflows branch master to release
Log:
=> chore: github workflows branch master to release

debian/changelog
release 1.5.8-1
Log: bump version to 1.5.8-1
=> chore: bump version to 1.5.8-1

debian/changelog
release 1.6.3-1
Log: bump version to 1.6.3-1
=> chore: bump version to 1.6.3-1

apps/ll-cli/src/main.cpp, libs/linglong/src/linglong/builder/linglong_builder.cpp, libs/linglong/src/linglong/cli/cli.cpp, libs/linglong/src/linglong/cli/cli.h, libs/linglong/src/linglong/package/fuzzy_reference.cpp, libs/linglong/src/linglong/package/reference.cpp, libs/linglong/src/linglong/package/uab_packager.cpp, libs/linglong/src/linglong/package/version.cpp, libs/linglong/src/linglong/package/version_range.cpp, libs/linglong/src/linglong/package_manager/package_manager.cpp, libs/linglong/src/linglong/repo/client_factory.cpp, libs/linglong/src/linglong/repo/client_factory.h, libs/linglong/src/linglong/repo/config.cpp, libs/linglong/src/linglong/repo/ostree_repo.cpp, libs/linglong/src/linglong/repo/ostree_repo.h, libs/linglong/src/linglong/repo/repo_cache.cpp, libs/linglong/src/linglong/runtime/container.cpp, libs/linglong/src/linglong/runtime/container.h, libs/linglong/src/linglong/runtime/container_builder.cpp, libs/linglong/src/linglong/runtime/container_builder.h, libs/oci-cfg-generators/src/linglong/oci-cfg-generators/40_host_ipc.cpp, libs/utils/src/linglong/utils/packageinfo_handler.cpp, libs/utils/src/linglong/utils/packageinfo_handler.h, libs/utils/src/linglong/utils/serialize/json.h
=> sync upstream code

debian/linglong-bin.install
Add linyaps desktop to install file.
=> feat: install linyaps desktop

debian/changelog
=> chore: bump version 1.7.9-1

rpm/linglong.spec
fedora构建时会报错fPIE相关问题
Issue: https://github.com/OpenAtom-Linyaps/linyaps/issues/989
=> fix: build failed on fedora

debian/control
Remove erofsfuse version restrictions.
=> fix: remove erofsfuse version restrictions

debian/rules
=> fix: can not found ll-box in deepin

debian/control, debian/linglong-bin.install, debian/linglong-box.install, debian/rules, rpm/linglong.spec
Remove linglong-box packaging script.
=> chore: remove linglong-box packaging script

debian/linglong-bin.lintian-overrides
=> fix: lintian check error

libs/oci-cfg-generators/src/linglong/oci-cfg-generators/05_initialize.cpp
目前临时目录生成仅和时间有关, 运行应用时有概率重用其他用户的临时目录(包括生成缓存的临时目录),
这会导致应用没有权限访问临时目录, 从而影响应用运行
修改后临时目录根据时间, 用户ID和应用ID生成以保证唯一性
=> fix: temporary directories causes the app to fail to run

debian/patches/mount-some-dirs.patch
Add browser extensions dir to Mount dirs.
=> feat: add browser extensions dir

debian/patches/mount-some-dirs.patch
Mount /usr/share/dsg to container.
=> feat: mount /usr/share/dsg to container

debian/linglong-bin.install, debian/linglong-bin.postinst, debian/patches/add-linyaps-preloader.patch
=> fix: failed to patch

debian/control
=> chore: add package dependencies

debian/patches/0005-repo-token.patch
=> chore: update repo token patch

debian/rules
=> chore: fix build pacakge error

debian/control
Add new packaging dependencies and runtime dependencies.
=> chore: add new dependencies

.github/workflows/call-auto-tag.yml
modify organization to deepin-community.
=> chore: update workflows
